/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package clipper;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.DefaultListModel;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jakubwawak
 */
public class main_window extends javax.swing.JFrame {
    final String version = "v1.0.0B2";
    
    DefaultListModel<String> clipboard_list_model;
    
    int index = -1;
    ClipBoardListener clipboard_evt;
    
    /**
     * Creates new form main_window
     */
    public main_window() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        super("Clipper");


        initComponents();
        prepare_list();
        
        version_label.setText(version);
        
        clipboard_evt = new ClipBoardListener(clipboard_list_model,clipper_jList);
        Thread thread = new Thread(clipboard_evt);
        thread.start();

        setVisible(true);
    }
    
    void prepare_list(){
        
        clipboard_list_model = new DefaultListModel<String>();
        clipper_jList.setModel(clipboard_list_model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clipper_jList = new javax.swing.JList<>();
        copy_to_c_button = new javax.swing.JButton();
        more_data_button = new javax.swing.JButton();
        database_button = new javax.swing.JButton();
        version_label = new javax.swing.JLabel();
        info_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clipper_jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        clipper_jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clipper_jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clipper_jList);

        copy_to_c_button.setText("Copy to clipboard");
        copy_to_c_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy_to_c_buttonActionPerformed(evt);
            }
        });

        more_data_button.setText("More data");
        more_data_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                more_data_buttonActionPerformed(evt);
            }
        });

        database_button.setText("Database");

        version_label.setText("jLabel1");

        info_button.setText("?");
        info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(version_label))
                    .addComponent(copy_to_c_button, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(more_data_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(database_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copy_to_c_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(more_data_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(database_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version_label)
                    .addComponent(info_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clipper_jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clipper_jListMouseClicked
        copy_to_c_button.setText("Copy to clipboard");
        System.out.println("Sel val: "+clipper_jList.getSelectedValue());
        index = clipper_jList.getSelectedIndex();
        System.out.println("Sel indx: "+Integer.toString(index));
    }//GEN-LAST:event_clipper_jListMouseClicked

    private void more_data_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_more_data_buttonActionPerformed
        if (index != -1){
            new more_info_window(this,true,clipboard_evt.contener,index);
            clipper_jList.setModel(clipboard_evt.contener.return_listmodel());
        }
    }//GEN-LAST:event_more_data_buttonActionPerformed

    private void copy_to_c_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy_to_c_buttonActionPerformed
        StringSelection stringSelection = new StringSelection(clipboard_evt.contener.get(index).raw_data);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        copy_to_c_button.setText("Copied");
    }//GEN-LAST:event_copy_to_c_buttonActionPerformed

    private void info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> clipper_jList;
    private javax.swing.JButton copy_to_c_button;
    private javax.swing.JButton database_button;
    private javax.swing.JButton info_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton more_data_button;
    private javax.swing.JLabel version_label;
    // End of variables declaration//GEN-END:variables
}
